### ISSUE TITLE
"Test the Experiment" instructions fail

### ISSUE THREAD

**Issue by earcanal** [expfactory-experiments/breath-counting-task#5]
When I follow https://expfactory.github.io/expfactory/contribute#test-the-experiment, I get

    $ singularity pull --name expfactory.test shub://expfactory/expfactory:test
    ERROR: Unknown command 'pull'

**Comment by earcanal** [comment]
This was a distribution issue; `pull` is in 2.3.2-dist, but not 2.2.

**Comment by earcanal** [comment]
$ singularity pull --name expfactory.test shub://expfactory/expfactory:test
    Progress |===================================| 100.0% 

    gzip: ./expfactory.test.img.gz: not in gzip format
    ERROR Error extracting image, cleaning up.
    ERROR: pulling container failed!

**Comment by vsoch** [comment]
Oh sorry about that! I would use the 2.4 distribution. I'll update the docs when. I'm back at keyboard.

**Comment by earcanal** [comment]
Latest packaged version appears to 2.3.2-dist (NeuroDebian).

**Comment by vsoch** [comment]
Oh! Further clarification - you should install it from the tagged release or a branch on GitHub.

**Comment by vsoch** [comment]
hey @earcanal ! Just a heads up I have most of the work done for a Docker version of expfactory - it's a lot easier to use because we avoid all these little bugs we've been hitting.  It's not completely done, but so far I'm very happy with it! Specifically, you would:

 1. Use a provided container `vanessa/expfactory-builder` to generate a Dockerfile for your experiment container (important for reproducibility)
 2. Build it and run it!

The cool part is that you can shell inside and install a new experiment with a command, and easily run on local host and map to your data folder, etc.

https://github.com/expfactory/expfactory/tree/master/expfactory/templates/build/docker/builder

It's not quite ready for testing (there are a few bugs I want to work out, and a few things I want to make easier) so for now this is just for your FYI - I'll ping you when I've redone the docs that you were looking at previously to reflect a more finalized version of the above.

**Comment by earcanal** [comment]
Closing now that things have moved on (to Docker).
